## PART A:

In [27]:
import pandas as pd

In [28]:
data = pd.read_csv("weather.csv")

### Basic Exploration

In [29]:
data.head()

,temp,location,clouds,pressure,rain,time_stamp,humidity,wind
0,42.42,Back Bay,1.0,1012.14,0.1228,1545003901,0.77,11.25
1,42.43,Beacon Hill,1.0,1012.15,0.1846,1545003901,0.76,11.32
2,42.50,Boston University,1.0,1012.15,0.1089,1545003901,0.76,11.07
3,42.11,Fenway,1.0,1012.13,0.0969,1545003901,0.77,11.09
4,43.13,Financial District,1.0,1012.14,0.1786,1545003901,0.75,11.49

In [30]:
data.tail()

,temp,location,clouds,pressure,rain,time_stamp,humidity,wind
6271,44.72,North Station,0.89,1000.69,NaN,1543819974,0.96,1.52
6272,44.85,Northeastern University,0.88,1000.71,NaN,1543819974,0.96,1.54
6273,44.82,South Station,0.89,1000.70,NaN,1543819974,0.96,1.54
6274,44.78,Theatre District,0.89,1000.70,NaN,1543819974,0.96,1.54
6275,44.69,West End,0.89,1000.70,NaN,1543819974,0.96,1.52

In [31]:
data.shape

(6276, 8)

In [32]:
data.columns

Index(['temp', 'location', 'clouds', 'pressure', 'rain', 'time_stamp',
       'humidity', 'wind'],
      dtype='str')

### Data Cleaning

In [33]:
data.isnull().sum()

temp             0
location         0
clouds           0
pressure         0
rain          5382
time_stamp       0
humidity         0
wind             0
dtype: int64

In [34]:
data.fillna(0)

,temp,location,clouds,pressure,rain,time_stamp,humidity,wind
0,42.42,Back Bay,1.00,1012.14,0.1228,1545003901,0.77,11.25
1,42.43,Beacon Hill,1.00,1012.15,0.1846,1545003901,0.76,11.32
2,42.50,Boston University,1.00,1012.15,0.1089,1545003901,0.76,11.07
3,42.11,Fenway,1.00,1012.13,0.0969,1545003901,0.77,11.09
4,43.13,Financial District,1.00,1012.14,0.1786,1545003901,0.75,11.49
...,...,...,...,...,...,...,...,...
6271,44.72,North Station,0.89,1000.69,0.0000,1543819974,0.96,1.52
6272,44.85,Northeastern University,0.88,1000.71,0.0000,1543819974,0.96,1.54
6273,44.82,South Station,0.89,1000.70,0.0000,1543819974,0.96,1.54
6274,44.78,Theatre District,0.89,1000.70,0.0000,1543819974,0.96,1.54
6275,44.69,West End,0.89,1000.70,0.0000,1543819974,0.96,1.52

### Descriptive Statistics

In [35]:
data.describe()

,temp,clouds,pressure,rain,time_stamp,humidity,wind
count,6276.000000,6276.000000,6276.000000,894.000000,6.276000e+03,6276.000000,6276.000000
mean,39.090475,0.677777,1008.445209,0.057652,1.543857e+09,0.763985,6.802812
std,6.022055,0.314284,12.870775,0.100758,6.659340e+05,0.127340,3.633466
min,19.620000,0.000000,988.250000,0.000200,1.543204e+09,0.450000,0.290000
25%,36.077500,0.440000,997.747500,0.004900,1.543387e+09,0.670000,3.517500
50%,40.130000,0.780000,1007.660000,0.014850,1.543514e+09,0.760000,6.570000
75%,42.832500,0.970000,1018.480000,0.060925,1.544691e+09,0.890000,9.920000
max,55.410000,1.000000,1035.120000,0.780700,1.545159e+09,0.990000,18.180000

In [36]:
print(f"Temperature Mean : {data['temp'].mean()}")
print(f"Minimum Temperature: {data['temp'].min()}")
print(f"Maximum Temperature: {data['temp'].max()}")
print(f"Standard Deviation of Temperature: {data['temp'].std()}")

Temperature Mean : 39.09047482472913
Minimum Temperature: 19.62
Maximum Temperature: 55.41
Standard Deviation of Temperature: 6.022055153228792

### Categorical Analysis

In [37]:
data['location'].nunique()

12

In [38]:
data['location'].value_counts()

location
Back Bay                   523
Beacon Hill                523
Boston University          523
Fenway                     523
Financial District         523
Haymarket Square           523
North End                  523
North Station              523
Northeastern University    523
South Station              523
Theatre District           523
West End                   523
Name: count, dtype: int64

## PART B:

In [40]:
filtered = data[(data['temp'] > 40) & (data['humidity'] > 0.7)]
filtered

,temp,location,clouds,pressure,rain,time_stamp,humidity,wind
0,42.42,Back Bay,1.00,1012.14,0.1228,1545003901,0.77,11.25
1,42.43,Beacon Hill,1.00,1012.15,0.1846,1545003901,0.76,11.32
2,42.50,Boston University,1.00,1012.15,0.1089,1545003901,0.76,11.07
3,42.11,Fenway,1.00,1012.13,0.0969,1545003901,0.77,11.09
4,43.13,Financial District,1.00,1012.14,0.1786,1545003901,0.75,11.49
...,...,...,...,...,...,...,...,...
6271,44.72,North Station,0.89,1000.69,NaN,1543819974,0.96,1.52
6272,44.85,Northeastern University,0.88,1000.71,NaN,1543819974,0.96,1.54
6273,44.82,South Station,0.89,1000.70,NaN,1543819974,0.96,1.54
6274,44.78,Theatre District,0.89,1000.70,NaN,1543819974,0.96,1.54
6275,44.69,West End,0.89,1000.70,NaN,1543819974,0.96,1.52

In [42]:
data['temp_fahreneit'] = (data['temp'] * (9/5)) + 32
data

,temp,location,clouds,pressure,rain,time_stamp,humidity,wind,temp_fahreneit
0,42.42,Back Bay,1.00,1012.14,0.1228,1545003901,0.77,11.25,108.356
1,42.43,Beacon Hill,1.00,1012.15,0.1846,1545003901,0.76,11.32,108.374
2,42.50,Boston University,1.00,1012.15,0.1089,1545003901,0.76,11.07,108.500
3,42.11,Fenway,1.00,1012.13,0.0969,1545003901,0.77,11.09,107.798
4,43.13,Financial District,1.00,1012.14,0.1786,1545003901,0.75,11.49,109.634
...,...,...,...,...,...,...,...,...,...
6271,44.72,North Station,0.89,1000.69,NaN,1543819974,0.96,1.52,112.496
6272,44.85,Northeastern University,0.88,1000.71,NaN,1543819974,0.96,1.54,112.730
6273,44.82,South Station,0.89,1000.70,NaN,1543819974,0.96,1.54,112.676
6274,44.78,Theatre District,0.89,1000.70,NaN,1543819974,0.96,1.54,112.604
6275,44.69,West End,0.89,1000.70,NaN,1543819974,0.96,1.52,112.442

In [44]:
data_sorted = data.sort_values(by='temp', ascending=False)
data_sorted

,temp,location,clouds,pressure,rain,time_stamp,humidity,wind,temp_fahreneit
5344,55.41,Northeastern University,0.47,999.25,NaN,1543855974,0.68,16.23,131.738
5346,55.38,Theatre District,0.48,999.24,NaN,1543855974,0.68,16.08,131.684
5339,55.37,Fenway,0.46,999.25,NaN,1543855974,0.68,16.40,131.666
5345,55.33,South Station,0.48,999.24,NaN,1543855974,0.68,15.97,131.594
5343,55.32,North Station,0.48,999.23,NaN,1543855974,0.68,16.27,131.576
...,...,...,...,...,...,...,...,...,...
2445,19.78,Boston University,0.61,1030.21,NaN,1544690701,0.61,3.56,67.604
5174,19.73,Boston University,0.43,1031.08,NaN,1544697901,0.63,3.65,67.514
598,19.67,Fenway,0.43,1031.08,NaN,1544697902,0.64,3.65,67.406
2155,19.66,Fenway,0.39,1030.72,NaN,1544694301,0.64,3.72,67.388
2154,19.62,Boston University,0.39,1030.72,NaN,1544694301,0.64,3.70,67.316

In [45]:
grouped = data.groupby('location')['temp'].mean()
grouped

location
Back Bay                   39.082122
Beacon Hill                39.047285
Boston University          39.047744
Fenway                     38.964379
Financial District         39.410822
Haymarket Square           39.067897
North End                  39.090841
North Station              39.035315
Northeastern University    38.975086
South Station              39.394092
Theatre District           38.986711
West End                   38.983403
Name: temp, dtype: float64

## PART C:

### Q1. What is EDA (Exploratory Data Analysis)?

EDA (Exploratory Data Analysis) is the process of **analyzing and understanding a dataset before applying any machine learning model**.  
It helps us explore the data using **summary statistics and visualizations**.

### In EDA, we:

- Check the structure of data (rows and columns)  
- Identify missing values  
- Understand data types (numerical or categorical)  
- Analyze patterns, trends, and relationships  

###  Why EDA is Important:

- It helps us **clean the data** (handle missing or incorrect values)  
- It helps us **understand the data better**  
- It helps in **detecting outliers or unusual values**  
- It ensures we use the **right model and features**

In [46]:
avg_temp = data['temp'].mean()
result = data[data['temp'] > avg_temp]
result

,temp,location,clouds,pressure,rain,time_stamp,humidity,wind,temp_fahreneit
0,42.42,Back Bay,1.00,1012.14,0.1228,1545003901,0.77,11.25,108.356
1,42.43,Beacon Hill,1.00,1012.15,0.1846,1545003901,0.76,11.32,108.374
2,42.50,Boston University,1.00,1012.15,0.1089,1545003901,0.76,11.07,108.500
3,42.11,Fenway,1.00,1012.13,0.0969,1545003901,0.77,11.09,107.798
4,43.13,Financial District,1.00,1012.14,0.1786,1545003901,0.75,11.49,109.634
...,...,...,...,...,...,...,...,...,...
6271,44.72,North Station,0.89,1000.69,NaN,1543819974,0.96,1.52,112.496
6272,44.85,Northeastern University,0.88,1000.71,NaN,1543819974,0.96,1.54,112.730
6273,44.82,South Station,0.89,1000.70,NaN,1543819974,0.96,1.54,112.676
6274,44.78,Theatre District,0.89,1000.70,NaN,1543819974,0.96,1.54,112.604
6275,44.69,West End,0.89,1000.70,NaN,1543819974,0.96,1.52,112.442

 Insights from `describe()` Function

The `describe()` function in Pandas provides a **statistical summary of numerical data**.  
It helps us understand the **distribution and behavior** of the dataset.

From `describe()`, we get:

- **Count** → Number of non-missing values in each column  
- **Mean** → Average value of the data  
- **Standard Deviation (std)** → Shows how much the data varies  
- **Minimum (min)** → Smallest value  
- **Maximum (max)** → Largest value  


Quartiles (Data Distribution)

- **25% (Q1)** → Lower values  
- **50% (Median)** → Middle value  
- **75% (Q3)** → Higher values  


Conclusion

The `describe()` function helps us:
- Understand data distribution  
- Identify outliers  
- Analyze spread of data

## PART D:

### PROMPT:
"Explain EDA steps using Pandas with examples"

## OUTPUT:

### Exploratory Data Analysis (EDA) with Pandas

EDA is the process of understanding your dataset before modeling. Here are the key steps:


### 1. Load the Data

```python
import pandas as pd

df = pd.read_csv('data.csv')
```


### 2. First Look at the Data

```python
df.head()        # First 5 rows
df.tail()        # Last 5 rows
df.shape         # (rows, columns)
df.columns       # Column names
df.dtypes        # Data types of each column
```


### 3. Summary Statistics

```python
df.describe()               # Stats for numeric columns (mean, std, min, max, etc.)
df.describe(include='all')  # Includes categorical columns too
```

Example output for a `temp` column:

| | temp |
|--|------|
| count | 100.0 |
| mean | 36.6 |
| std | 5.2 |
| min | 20.0 |
| max | 42.0 |


### 4. Check for Missing Values

```python
df.isnull().sum()                        # Count of nulls per column
df.isnull().sum() / len(df) * 100        # Null percentage per column
```

Handle missing values:

```python
df.dropna()                              # Drop rows with nulls
df['col'].fillna(df['col'].mean())       # Fill nulls with mean
```


### 5. Check for Duplicates

```python
df.duplicated().sum()    # Count duplicate rows
df.drop_duplicates()     # Remove duplicates
```


### 6. Value Counts (for Categorical Columns)

```python
df['gender'].value_counts()                    # Frequency of each category
df['gender'].value_counts(normalize=True)      # As proportions
```

Example output:

```
Male      60
Female    40
Name: gender, dtype: int64
```


### 7. Correlation Analysis

```python
df.corr()                              # Correlation matrix
df['sales'].corr(df['price'])          # Correlation between 2 columns
```

Heatmap visualization:

```python
import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.show()
```


### 8. Distribution of Numeric Columns

```python
df['age'].hist(bins=20)        # Histogram
df['age'].plot(kind='box')     # Boxplot to detect outliers
```


### 9. Groupby Analysis

```python
df.groupby('city')['sales'].mean()       # Average sales per city
df.groupby('gender')['salary'].sum()     # Total salary by gender
```


### 10. Outlier Detection

```python
Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1

outliers = df[(df['salary'] < Q1 - 1.5 * IQR) | (df['salary'] > Q3 + 1.5 * IQR)]
```


### Quick EDA Summary Table

| Step | Method |
|------|--------|
| Shape & types | `df.shape`, `df.dtypes` |
| Stats | `df.describe()` |
| Nulls | `df.isnull().sum()` |
| Duplicates | `df.duplicated().sum()` |
| Categories | `df.value_counts()` |
| Correlation | `df.corr()` |
| Outliers | IQR method |

These steps give you a solid understanding of your data before building any model!

### Evaluation Of Output:
The AI-generated explanation was correct and accurate. It properly explained the steps of EDA such as data loading, data cleaning, and data analysis using Pandas functions like head(), describe(), and isnull().

The examples provided were relevant and easy to understand. The output was also consistent with standard Pandas practices.